[sources.http_logs]
type = "http"
address = "0.0.0.0:8686"
encoding = "json"
headers=["*"]

[sinks.clickhouse]
type = "clickhouse"
inputs = ["http_logs"]
endpoint = "http://clickhouse:8123"
database = "logs_db"
table = "logs"
auth.strategy="basic"
auth.password="admin123"
auth.user="admin"
healthcheck.enabled=true
skip_unknown_fields=true